# Generated by Django 2.0.5 on 2018-08-06 14:23

import datetime
from django.db import migrations, models
import myform.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='报表文本项编码')),
                ('name', models.CharField(max_length=30, verbose_name='报表文本项名称')),
            ],
        ),
        migrations.CreateModel(
            name='FormTextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_time', models.DateField(auto_now_add=True, verbose_name='填报时间')),
                ('content', models.TextField(verbose_name='报表文本项内容')),
            ],
        ),
        migrations.CreateModel(
            name='MyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('number', models.CharField(max_length=30, verbose_name='报表编码')),
                ('formname', models.CharField(max_length=30, verbose_name='报表名称')),
                ('created_at', models.DateField(default=datetime.datetime(2018, 8, 6, 14, 23, 21, 204424), verbose_name='创建时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='测点编码')),
                ('name', models.CharField(max_length=30, verbose_name='测点名称')),
                ('crewnumber', models.CharField(default='', max_length=20, verbose_name='机组号')),
            ],
        ),
        migrations.CreateModel(
            name='PointData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_time', models.DateField(auto_now_add=True, verbose_name='填报时间')),
                ('pvalue', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='测点值')),
            ],
        ),
        migrations.CreateModel(
            name='PtypeUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=100, verbose_name='url名称')),
                ('url_data', models.CharField(max_length=100, verbose_name='监督类型对应url')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='指标编码')),
                ('name', models.CharField(max_length=30, verbose_name='指标名称')),
                ('unit', models.CharField(max_length=30, verbose_name='指标单位')),
                ('calculat_formula', models.CharField(max_length=50, null=True, verbose_name='指标计算公式')),
                ('stard_value', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='指标标准值')),
                ('stat_type', models.CharField(max_length=30, null=True, verbose_name='指标统计类型')),
                ('crewnumber', models.CharField(default='', max_length=20, verbose_name='机组号')),
            ],
        ),
        migrations.CreateModel(
            name='TargetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_time', models.DateField(auto_now_add=True, verbose_name='填报时间')),
                ('pvalue', models.CharField(max_length=20, null=True, verbose_name='指标值')),
                ('number', models.ForeignKey(on_delete=models.SET(myform.models.Point), related_name='指标数据', to='myform.Target', verbose_name='指标数据')),
            ],
        ),
    ]
