# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myform.models
import systemsettings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemsettings', '0001_initial'),
        ('myform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lbworkflow', '0002_auto_20171019_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='exe_depart',
            field=models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.Job), to='systemsettings.Job', verbose_name='指标责任岗位'),
        ),
        migrations.AddField(
            model_name='target',
            name='powerplants',
            field=models.ForeignKey(on_delete=models.SET(systemsettings.models.PowerPlants), related_name='指标电厂名称', to='systemsettings.PowerPlants', verbose_name='电厂名称'),
        ),
        migrations.AddField(
            model_name='target',
            name='ptype',
            field=models.ForeignKey(on_delete=models.SET(systemsettings.models.SupervisionType), related_name='指标监督专业', to='systemsettings.SupervisionType', verbose_name='监督专业'),
        ),
        migrations.AddField(
            model_name='ptypeurl',
            name='p_type',
            field=models.ForeignKey(on_delete=models.SET(systemsettings.models.SupervisionType), related_name='报表类型监督专业', to='systemsettings.SupervisionType', verbose_name='监督专业'),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='number',
            field=models.ForeignKey(on_delete=models.SET(myform.models.Point), related_name='测点编码', to='myform.Point', verbose_name='测点编码'),
        ),
        migrations.AddField(
            model_name='point',
            name='powerplants',
            field=models.ForeignKey(on_delete=models.SET(systemsettings.models.PowerPlants), related_name='测点编码名称', to='systemsettings.PowerPlants', verbose_name='电厂名称'),
        ),
        migrations.AddField(
            model_name='point',
            name='ptype',
            field=models.ForeignKey(on_delete=models.SET(systemsettings.models.SupervisionType), related_name='测点监督专业', to='systemsettings.SupervisionType', verbose_name='监督专业'),
        ),
        migrations.AddField(
            model_name='myform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='myform',
            name='exe_job',
            field=models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.Job), to='systemsettings.Job', verbose_name='报表填报责任岗位'),
        ),
        migrations.AddField(
            model_name='myform',
            name='pinstance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myform', to='lbworkflow.ProcessInstance', verbose_name='Process instance'),
        ),
        migrations.AddField(
            model_name='myform',
            name='powerplants',
            field=models.ForeignKey(on_delete=models.SET(systemsettings.models.PowerPlants), related_name='报表电厂名称', to='systemsettings.PowerPlants', verbose_name='电厂名称'),
        ),
        migrations.AddField(
            model_name='myform',
            name='ptype',
            field=models.ForeignKey(on_delete=models.SET(systemsettings.models.SupervisionType), related_name='报表监督专业', to='systemsettings.SupervisionType', verbose_name='监督专业'),
        ),
        migrations.AddField(
            model_name='formtextdata',
            name='number',
            field=models.ForeignKey(on_delete=models.SET(myform.models.FormText), to='myform.FormText', verbose_name='报表文本项编码'),
        ),
        migrations.AddField(
            model_name='formtext',
            name='power_plan',
            field=models.ForeignKey(default='', on_delete=models.SET(systemsettings.models.PowerPlants), related_name='报表电厂', to='systemsettings.PowerPlants', verbose_name='电厂编码'),
        ),
        migrations.AddField(
            model_name='formtext',
            name='type',
            field=models.ForeignKey(default='', on_delete=models.SET(systemsettings.models.SupervisionType), related_name='报表专业', to='systemsettings.SupervisionType', verbose_name='监督专业'),
        ),
    ]
