# Generated by Django 2.0.5 on 2018-08-06 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0002_auto_20180806_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 6, 14, 37, 50, 211372), verbose_name='创建时间'),
        ),
    ]
