# Generated by Django 2.0.5 on 2018-08-06 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0003_auto_20180806_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 6, 14, 46, 42, 530058), verbose_name='创建时间'),
        ),
    ]
