# Generated by Django 2.0.5 on 2018-08-11 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0007_auto_20180808_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 11, 15, 28, 17, 563995), verbose_name='创建时间'),
        ),
    ]
