# Generated by Django 2.0.5 on 2018-08-11 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0008_auto_20180811_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 11, 15, 29, 52, 706348), verbose_name='创建时间'),
        ),
    ]
