# Generated by Django 2.0.5 on 2018-08-15 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0011_auto_20180815_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 15, 9, 29, 9, 179789), verbose_name='创建时间'),
        ),
    ]
