# Generated by Django 2.0.5 on 2018-08-16 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0012_auto_20180815_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 16, 14, 35, 18, 346463), verbose_name='创建时间'),
        ),
    ]
