# Generated by Django 2.0.5 on 2018-08-16 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0013_auto_20180816_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 16, 16, 6, 32, 90589), verbose_name='创建时间'),
        ),
    ]
