# Generated by Django 2.0.5 on 2018-08-20 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0015_auto_20180820_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 20, 17, 2, 13, 703586), verbose_name='创建时间'),
        ),
    ]
