# Generated by Django 2.0.5 on 2018-08-22 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0016_auto_20180820_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 22, 10, 59, 20, 277332), verbose_name='创建时间'),
        ),
    ]
