# Generated by Django 2.0.5 on 2018-08-22 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0017_auto_20180822_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 22, 11, 2, 24, 257726), verbose_name='创建时间'),
        ),
    ]
