# Generated by Django 2.0.5 on 2018-08-23 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0018_auto_20180822_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 23, 15, 57, 1, 633849), verbose_name='创建时间'),
        ),
    ]
