# Generated by Django 2.0.5 on 2018-08-25 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0019_auto_20180825_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 25, 14, 31, 0, 15411), verbose_name='创建时间'),
        ),
    ]
