# Generated by Django 2.0.5 on 2018-08-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0019_auto_20180823_1557'),
        ('myform', '0020_auto_20180825_1431'),
    ]

    operations = [
    ]
