# Generated by Django 2.0.5 on 2018-08-27 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0021_merge_20180827_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 27, 16, 16, 49, 798190), verbose_name='创建时间'),
        ),
    ]
