# Generated by Django 2.0.5 on 2018-08-28 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0022_auto_20180827_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 17, 4, 57, 498022), verbose_name='创建时间'),
        ),
    ]
