# Generated by Django 2.0.5 on 2018-09-01 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0023_auto_20180828_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 9, 1, 15, 48, 26, 390727), verbose_name='创建时间'),
        ),
    ]
