# Generated by Django 2.0.5 on 2018-09-04 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0024_auto_20180901_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 9, 4, 14, 48, 42, 135997), verbose_name='创建时间'),
        ),
    ]
