# Generated by Django 2.0.5 on 2018-09-07 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0025_auto_20180904_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 9, 7, 12, 9, 38, 78647), verbose_name='创建时间'),
        ),
    ]
