# Generated by Django 2.0.5 on 2018-10-06 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0027_auto_20181006_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 10, 6, 16, 4, 29, 109574), verbose_name='创建时间'),
        ),
    ]
