# Generated by Django 2.0.5 on 2018-10-08 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0029_auto_20181008_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 10, 8, 9, 31, 26, 365023), verbose_name='创建时间'),
        ),
    ]
