# Generated by Django 2.0.5 on 2018-11-24 13:37

import datetime
from django.db import migrations, models
import myform.models
import systemsettings.models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0001_initial'),
        ('myform', '0030_auto_20181008_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='报表状态号')),
                ('state_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='报表状态名称')),
                ('spare1', models.CharField(blank=True, max_length=100, null=True, verbose_name='备用字段1')),
                ('spare2', models.CharField(blank=True, max_length=100, null=True, verbose_name='备用字段2')),
                ('edit_person', models.ForeignKey(blank=True, null=True, on_delete=models.SET(systemsettings.models.MyUser), to='systemsettings.MyUser', verbose_name='报表状态最后更新人')),
            ],
        ),
        migrations.AddField(
            model_name='myform',
            name='create_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(systemsettings.models.MyUser), to='systemsettings.MyUser', verbose_name='报表填报人'),
        ),
        migrations.AddField(
            model_name='myform',
            name='form_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='填报月份'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 13, 37, 37, 235283), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='myform',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(myform.models.Form_state), to='myform.Form_state', verbose_name='报表状态'),
        ),
    ]
