# Generated by Django 2.0.5 on 2018-11-24 16:27

import datetime
from django.db import migrations, models
import systemsettings.models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0001_initial'),
        ('myform', '0031_auto_20181124_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='myform',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(systemsettings.models.Company), related_name='报表公司名称', to='systemsettings.Company', verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 16, 27, 44, 360911), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='powerplants',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(systemsettings.models.PowerPlants), related_name='报表电厂名称', to='systemsettings.PowerPlants', verbose_name='电厂名称'),
        ),
    ]
