# Generated by Django 2.0.5 on 2018-11-24 17:42

import datetime
from django.db import migrations, models
import systemsettings.models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0001_initial'),
        ('myform', '0032_auto_20181124_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='myform',
            name='edit_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(systemsettings.models.MyUser), related_name='edit_person', to='systemsettings.MyUser', verbose_name='报表状态最后更新人'),
        ),
        migrations.AddField(
            model_name='myform',
            name='state_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='报表状态名称'),
        ),
        migrations.AddField(
            model_name='myform',
            name='state_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='报表状态号'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='create_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(systemsettings.models.MyUser), related_name='create_person', to='systemsettings.MyUser', verbose_name='报表填报人'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 17, 42, 32, 42027), verbose_name='创建时间'),
        ),
    ]
