# Generated by Django 2.0.5 on 2018-11-24 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0033_auto_20181124_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myform',
            name='state',
        ),
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 11, 24, 17, 44, 12, 695667), verbose_name='创建时间'),
        ),
    ]
