# Generated by Django 2.0.5 on 2018-12-11 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0034_auto_20181124_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 12, 11, 11, 3, 24, 993377), verbose_name='创建时间'),
        ),
    ]
