# Generated by Django 2.0.5 on 2018-12-11 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0035_auto_20181211_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 12, 11, 11, 5, 33, 501238), verbose_name='创建时间'),
        ),
    ]
