# Generated by Django 2.0.5 on 2019-02-14 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0036_auto_20181211_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 15, 58, 10, 786189), verbose_name='创建时间'),
        ),
    ]
