# Generated by Django 2.0.5 on 2019-02-27 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0037_auto_20190214_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 2, 27, 9, 43, 8, 595289), verbose_name='创建时间'),
        ),
    ]
