# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problemlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('name', models.CharField(max_length=30, verbose_name='问题名称')),
                ('number', models.CharField(max_length=30, verbose_name='问题编码')),
                ('source', models.CharField(max_length=30, verbose_name='问题来源')),
                ('desc', models.CharField(max_length=30, null=True, verbose_name='问题描述')),
                ('dis_time', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('rect_time', models.DateTimeField(auto_now_add=True, verbose_name='整改时间')),
                ('cause', models.CharField(max_length=30, null=True, verbose_name='问题原因')),
                ('advise', models.CharField(max_length=30, null=True, verbose_name='整改建议')),
                ('hand_info', models.CharField(max_length=30, null=True, verbose_name='处理情况')),
                ('state', models.CharField(default='拟定', max_length=30, verbose_name='状态')),
                ('level', models.SmallIntegerField(null=True, verbose_name='问题等级')),
                ('accessory', models.FileField(null=True, upload_to='pro/', verbose_name='附件')),
            ],
            options={
                'verbose_name': '问题记录表',
            },
        ),
    ]
