# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import systemsettings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qua25', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comnumber', models.CharField(max_length=30, verbose_name='公司编码')),
                ('comname', models.CharField(max_length=30, verbose_name='公司名称')),
                ('comsimplename', models.CharField(max_length=15, verbose_name='公司简称')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departnumber', models.CharField(max_length=30, verbose_name='部门编码')),
                ('departname', models.CharField(max_length=30, verbose_name='部门名称')),
                ('simple_name', models.CharField(max_length=30, null=True, verbose_name='部门简称')),
                ('company', models.ForeignKey(on_delete=models.SET(systemsettings.models.Company), to='systemsettings.Company', verbose_name='所属公司')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='台账编号')),
                ('name', models.CharField(max_length=30, verbose_name='台账名称')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('last_updated_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='最后更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='设备专业编码')),
                ('name', models.CharField(max_length=10, verbose_name='设备专业名称')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobnumber', models.CharField(max_length=30, verbose_name='岗位编码')),
                ('jobname', models.CharField(max_length=30, verbose_name='岗位名称')),
                ('simple_name', models.CharField(max_length=30, null=True, verbose_name='岗位简称')),
                ('company', models.ForeignKey(on_delete=models.SET(systemsettings.models.Company), to='systemsettings.Company', verbose_name='所属公司')),
            ],
        ),
        migrations.CreateModel(
            name='KKS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KKS_code', models.CharField(max_length=30, verbose_name='KKS编码')),
                ('KKS_codename', models.CharField(max_length=30, verbose_name='KKS编码名称')),
                ('place', models.ForeignKey(on_delete=models.SET('systemsettings.Company'), to='systemsettings.Company', verbose_name='公司名称')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='菜单名称')),
                ('order', models.SmallIntegerField(blank=True, default=1, verbose_name='排序')),
                ('is_active', models.SmallIntegerField(default=1, verbose_name='是否激活')),
                ('level', models.SmallIntegerField(null=True, verbose_name='菜单级别')),
                ('url', models.URLField(verbose_name='菜单路由')),
                ('font_class', models.CharField(max_length=100, null=True, verbose_name='字体图标类型')),
                ('number', models.CharField(default='', max_length=3, verbose_name='菜单编号')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=models.SET('self'), to='systemsettings.Menu', verbose_name='父级菜单')),
            ],
        ),
        migrations.CreateModel(
            name='MyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='责任组编号')),
                ('name', models.CharField(max_length=30, verbose_name='责任组名称')),
                ('place', models.ForeignKey(on_delete=models.SET(systemsettings.models.Company), to='systemsettings.Company', verbose_name='公司名称')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='工号')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('state', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('headimage', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='头像')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='聘用日期')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='终止日期')),
                ('is_activate', models.SmallIntegerField(default=1, verbose_name='是否激活')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=models.SET(systemsettings.models.Company), to='systemsettings.Company', verbose_name='公司名称')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=models.SET(systemsettings.models.Department), to='systemsettings.Department', verbose_name='部门名称')),
                ('equipment_major', models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.EquipmentMajor), to='systemsettings.EquipmentMajor', verbose_name='设备专业编码')),
                ('group', models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.MyGroup), to='systemsettings.MyGroup', verbose_name='人员所属责任组')),
                ('jobname', models.ForeignKey(blank=True, null=True, on_delete=models.SET(systemsettings.models.Job), to='systemsettings.Job', verbose_name='岗位名称')),
                ('quas', models.ManyToManyField(related_name='基本人员资质', to='qua25.Qua', verbose_name='人员资质')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='操作名称')),
                ('url', models.URLField(blank=True, null=True, verbose_name='排序')),
                ('is_active', models.SmallIntegerField(default=1, verbose_name='是否激活')),
                ('key', models.CharField(max_length=10, verbose_name='关键词')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=models.SET(systemsettings.models.Menu), to='systemsettings.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='PowerPlants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pownumber', models.CharField(max_length=30, verbose_name='电厂编码')),
                ('powname', models.CharField(max_length=30, verbose_name='电厂名称')),
                ('powsimplename', models.CharField(max_length=15, verbose_name='简称')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='角色名称')),
                ('is_activate', models.SmallIntegerField(default=1, verbose_name='是否被选用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('operations', models.ManyToManyField(to='systemsettings.Operation', verbose_name='操作')),
            ],
        ),
        migrations.CreateModel(
            name='Stard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='标准编码')),
                ('name', models.CharField(max_length=30, verbose_name='标准名称')),
                ('smallnumber', models.CharField(max_length=30, verbose_name='标准号')),
                ('type', models.CharField(max_length=10, verbose_name='标准类型')),
                ('V_number', models.CharField(max_length=10, verbose_name='标准版本')),
                ('updated_time', models.DateTimeField(verbose_name='更新时间')),
                ('place', models.ForeignKey(on_delete=models.SET('systemsettings.Company'), to='systemsettings.Company', verbose_name='公司名称')),
                ('publisher', models.ForeignKey(on_delete=models.SET(systemsettings.models.Department), to='systemsettings.Department', verbose_name='标准发布单位')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='监督专业编码')),
                ('name', models.CharField(max_length=10, verbose_name='监督专业名称')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamnumber', models.CharField(max_length=30, verbose_name='班组编码')),
                ('teamname', models.CharField(max_length=30, verbose_name='班组名称')),
                ('simple_name', models.CharField(max_length=30, null=True, verbose_name='班组简称')),
                ('department', models.ForeignKey(on_delete=models.SET(systemsettings.models.Department), to='systemsettings.Department', verbose_name='所属部门')),
            ],
        ),
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='工作区域编码')),
                ('name', models.CharField(max_length=10, verbose_name='工作区域名称')),
                ('place', models.ForeignKey(on_delete=models.SET('systemsettings.Company'), to='systemsettings.Company', verbose_name='公司名称')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='roles',
            field=models.ManyToManyField(to='systemsettings.Role', verbose_name='绑定角色'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='supervision_major',
            field=models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.SupervisionType), to='systemsettings.SupervisionType', verbose_name='监督专业编码'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.OneToOneField(on_delete=models.SET(django.contrib.auth.models.User), to=settings.AUTH_USER_MODEL, verbose_name='内置用户'),
        ),
        migrations.AddField(
            model_name='equipmentcount',
            name='equipment_major',
            field=models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.EquipmentMajor), to='systemsettings.EquipmentMajor', verbose_name='设备专业'),
        ),
        migrations.AddField(
            model_name='equipmentcount',
            name='place',
            field=models.ForeignKey(on_delete=models.SET('systemsettings.Company'), to='systemsettings.Company', verbose_name='公司名称'),
        ),
    ]
