# Generated by Django 2.0.5 on 2019-02-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0002_supervisiontype_form_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='kks',
            name='KKs_organid',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='KKS电厂接口id'),
        ),
        migrations.AlterField(
            model_name='kks',
            name='KKS_code',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='KKS编码'),
        ),
        migrations.AlterField(
            model_name='kks',
            name='KKS_codename',
            field=models.TextField(blank=True, default='', null=True, verbose_name='KKS编码名称'),
        ),
    ]
