# Generated by Django 2.0.5 on 2019-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0003_auto_20190225_1710'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='mygroup',
        #     name='spare1',
        #     field=models.CharField(blank=True, max_length=30, null=True, verbose_name='备用字段1'),
        # ),
        # migrations.AddField(
        #     model_name='mygroup',
        #     name='spare2',
        #     field=models.CharField(blank=True, max_length=30, null=True, verbose_name='备用字段2'),
        # ),
        # migrations.AddField(
        #     model_name='supervisiontype',
        #     name='form_use',
        #     field=models.CharField(max_length=10, null=True, verbose_name='报表使用'),
        # ),
    ]
