# Generated by Django 2.0.5 on 2019-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0003_auto_20190225_1623'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='supervisiontype',
        #     name='form_use',
        #     field=models.CharField(max_length=10, null=True, verbose_name='报表使用'),
        # ),
    ]
