# Generated by Django 2.0.5 on 2019-02-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0004_supervisiontype_form_use'),
        ('systemsettings', '0004_auto_20190226_1022'),
    ]

    operations = [
    ]
