# Generated by Django 2.0.5 on 2019-02-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0005_merge_20190227_1536'),
        ('systemsettings', '0005_merge_20190227_0938'),
    ]

    operations = [
    ]
