# Generated by Django 2.0.5 on 2019-03-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0006_merge_20190228_1438'),
        ('systemsettings', '0006_auto_20190228_1047'),
    ]

    operations = [
    ]
