# Generated by Django 2.0.5 on 2019-03-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_qua', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='staffqua',
        #     name='company_id',
        #     field=models.SmallIntegerField(default=7, null=True, verbose_name='对应公司id'),
        # ),
    ]
