# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models
import standard.models
import systemsettings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemsettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=40, null=True, verbose_name='指标名称')),
                ('sis_text', models.CharField(max_length=50, null=True, verbose_name='sis测点')),
                ('standard_value', models.CharField(max_length=20, null=True, verbose_name='标准值')),
                ('upper_limit_value', models.CharField(max_length=20, null=True, verbose_name='上限值')),
                ('lower_limit_value', models.CharField(max_length=20, null=True, verbose_name='下限值')),
                ('is_activate', models.SmallIntegerField(default=1, null=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '指标定义详情',
            },
        ),
        migrations.CreateModel(
            name='StandardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='指标名称')),
                ('sis_text', models.CharField(max_length=10, null=True, verbose_name='sis测点')),
                ('measured_value', models.CharField(max_length=20, null=True, verbose_name='测量值')),
                ('sis_modify', models.CharField(max_length=20, null=True, verbose_name='sis修改值')),
                ('standard_value', models.CharField(max_length=20, null=True, verbose_name='标准值')),
                ('upper_limit_value', models.CharField(max_length=20, null=True, verbose_name='上限值')),
                ('lower_limit_value', models.CharField(max_length=20, null=True, verbose_name='下限值')),
                ('is_activate', models.SmallIntegerField(default=1, null=True, verbose_name='是否激活')),
                ('last_updated_by', models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='指标最后修改人', to='systemsettings.MyUser', verbose_name='指标最后修改人')),
                ('maintenance_staff', models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='维护人员', to='systemsettings.MyUser', verbose_name='维护人员')),
            ],
            options={
                'verbose_name': '指标填报详情',
            },
        ),
        migrations.CreateModel(
            name='StandardFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, null=True, verbose_name='指标填报编号')),
                ('describe', models.CharField(max_length=50, null=True, verbose_name='指标填报描述')),
                ('state', models.CharField(default='拟定', max_length=20, verbose_name='状态')),
                ('fill_time', models.DateTimeField(auto_now_add=True, verbose_name='填报日期')),
                ('place', models.CharField(max_length=20, null=True, verbose_name='地点')),
                ('is_activate', models.SmallIntegerField(default=1, null=True, verbose_name='是否激活')),
                ('Supervision_type', models.ForeignKey(on_delete=models.SET(systemsettings.models.SupervisionType), related_name='指标填报监督类型', to='systemsettings.SupervisionType', verbose_name='监督类型')),
            ],
            options={
                'verbose_name': '指标填报列表',
            },
        ),
        migrations.CreateModel(
            name='StandardList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, null=True, verbose_name='指标定义编号')),
                ('describe', models.CharField(max_length=50, null=True, verbose_name='指标定义描述')),
                ('cycle', models.CharField(max_length=10, null=True, verbose_name='指标填报周期')),
                ('state', models.CharField(default='拟定', max_length=20, verbose_name='状态')),
                ('is_activate', models.SmallIntegerField(default=1, null=True, verbose_name='是否激活')),
                ('Supervision_type', models.ForeignKey(on_delete=models.SET(systemsettings.models.SupervisionType), related_name='指标定义监督类型', to='systemsettings.SupervisionType', verbose_name='监督类型')),
            ],
            options={
                'verbose_name': '指标定义列表',
            },
        ),
        migrations.AddField(
            model_name='standardfill',
            name='definition',
            field=models.ForeignKey(on_delete=models.SET(standard.models.StandardList), related_name='指标定义编号', to='standard.StandardList', verbose_name='指标定义编号'),
        ),
        migrations.AddField(
            model_name='standardentry',
            name='standard_fill',
            field=models.ForeignKey(on_delete=models.SET(standard.models.StandardFill), related_name='指标填报列表', to='standard.StandardFill', verbose_name='指标填报列表'),
        ),
        migrations.AddField(
            model_name='standarddetails',
            name='definition',
            field=models.ForeignKey(on_delete=models.SET(standard.models.StandardList), related_name='指标类型', to='standard.StandardList', verbose_name='指标类型'),
        ),
        migrations.AddField(
            model_name='standarddetails',
            name='maintenance_staff',
            field=models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='指标维护人员', to='systemsettings.MyUser', verbose_name='维护人员'),
        ),
    ]
