# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=10, verbose_name='节点名称')),
                ('resource', models.CharField(max_length=10, verbose_name='岗位流转类型')),
                ('operators_job', models.TextField(blank=True, verbose_name='操作者岗位')),
            ],
        ),
        migrations.CreateModel(
            name='MyProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myprocess_name', models.CharField(max_length=30, verbose_name='流程名称')),
                ('app_name', models.CharField(max_length=30, verbose_name='对应表单')),
            ],
        ),
    ]
