# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models
import lbworkflow.models.config
import myworkflow.models
import systemsettings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemsettings', '0001_initial'),
        ('myworkflow', '0001_initial'),
        ('lbworkflow', '0002_auto_20171019_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprocess',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(systemsettings.models.Company), to='systemsettings.Company', verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='myprocess',
            name='process',
            field=models.OneToOneField(on_delete=models.SET(lbworkflow.models.config.Process), to='lbworkflow.Process', verbose_name='关联lb工作流程'),
        ),
        migrations.AddField(
            model_name='myprocess',
            name='supervision_major',
            field=models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.SupervisionType), to='systemsettings.SupervisionType', verbose_name='监督专业编码'),
        ),
        migrations.AddField(
            model_name='mynode',
            name='myprocess',
            field=models.ForeignKey(on_delete=models.SET(myworkflow.models.MyProcess), to='myworkflow.MyProcess', verbose_name='所属流程'),
        ),
        migrations.AddField(
            model_name='mynode',
            name='node',
            field=models.OneToOneField(on_delete=models.SET(lbworkflow.models.config.Node), to='lbworkflow.Node', verbose_name='关联lb流程节点'),
        ),
    ]
