# Generated by Django 2.0.5 on 2018-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkflow', '0002_auto_20180806_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynode',
            name='is_activate',
            field=models.SmallIntegerField(default=1, verbose_name='是否激活'),
        ),
        migrations.AddField(
            model_name='myprocess',
            name='is_activate',
            field=models.SmallIntegerField(default=1, verbose_name='是否激活'),
        ),
    ]
