# Generated by Django 2.0.5 on 2018-08-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkflow', '0003_auto_20180808_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprocess',
            name='app_object_id',
            field=models.SmallIntegerField(default=0, verbose_name='具体表单记录'),
        ),
    ]
