# Generated by Django 2.0.5 on 2018-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkflow', '0004_myprocess_app_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprocess',
            name='app_object_id',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='具体表单记录'),
        ),
    ]
