# Generated by Django 2.0.5 on 2018-08-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkflow', '0006_auto_20180815_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprocess',
            name='app_object_id',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='具体表单记录'),
        ),
    ]
