# Generated by Django 2.0.5 on 2019-01-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkflow', '0007_auto_20180815_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='审批节点名称')),
                ('approve_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='审批人')),
                ('created_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('approve_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='审批状态')),
                ('content', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('process_id', models.IntegerField(default=1, verbose_name='流程编号')),
            ],
        ),
    ]
