# Generated by Django 2.0.5 on 2019-01-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkflow', '0008_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
    ]
