# Generated by Django 2.0.5 on 2018-08-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekworktask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekworktask',
            name='tanchuang',
            field=models.SmallIntegerField(default='0', verbose_name='是否已弹窗'),
        ),
    ]
