# Generated by Django 2.0.5 on 2018-08-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekworktask', '0002_weekworktask_tanchuang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekworktask',
            name='tanchuang',
        ),
    ]
