# Generated by Django 2.0.5 on 2019-02-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekworktask', '0003_remove_weekworktask_tanchuang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekworktask',
            name='plan',
            field=models.ForeignKey(on_delete=models.SET('weekworkplan.WeekWorkPlan'), to='weekworkplan.WeekWorkPlan', verbose_name='周期检测计划名称'),
        ),
    ]
