# Generated by Django 2.0.5 on 2019-02-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekworktask', '0004_auto_20190214_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekworktask',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='weekworktask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('systemsettings.MyUser'), related_name='周期检测任务创建人', to='systemsettings.MyUser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='weekworktask',
            name='last_updated_at',
            field=models.DateTimeField(null=True, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='weekworktask',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('systemsettings.MyUser'), related_name='周期检测任务最后更新人', to='systemsettings.MyUser', verbose_name='最后更新人'),
        ),
        migrations.AlterField(
            model_name='weekworktask',
            name='number',
            field=models.CharField(max_length=30, null=True, verbose_name='周期检测任务编码'),
        ),
        migrations.AlterField(
            model_name='weekworktask',
            name='task_start_time',
            field=models.DateField(null=True, verbose_name='计划开始时间'),
        ),
        migrations.AlterField(
            model_name='weekworktask',
            name='time_limit',
            field=models.CharField(max_length=10, null=True, verbose_name='完成时限'),
        ),
    ]
