# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemsettings', '0001_initial'),
        ('lbworkflow', '0002_auto_20171019_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekWorkPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('last_updated_at', models.DateTimeField(verbose_name='最后更新时间')),
                ('enclosure', models.FileField(null=True, upload_to='Plan/', verbose_name='附件')),
                ('is_activate', models.SmallIntegerField(default=1, null=True, verbose_name='是否激活')),
                ('number', models.CharField(max_length=30, verbose_name='周期检测计划编码')),
                ('plan', models.CharField(max_length=20, verbose_name='周期检测计划名称')),
                ('third_org', models.CharField(max_length=20, verbose_name='第三方机构')),
                ('rate_desc', models.CharField(max_length=50, verbose_name='频率')),
                ('rate_code', models.CharField(max_length=50, verbose_name='频率代码')),
                ('time_limit', models.CharField(max_length=10, verbose_name='完成时限')),
                ('state', models.CharField(default='新建', max_length=5, verbose_name='状态')),
                ('plan_time', models.DateField(verbose_name='策划时间')),
                ('created_by', models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='检测计划创建人', to='systemsettings.MyUser', verbose_name='创建人')),
                ('execute_user', models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='检测计划执行人', to='systemsettings.MyUser', verbose_name='执行人')),
                ('last_updated_by', models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='检测计划最后更新人', to='systemsettings.MyUser', verbose_name='最后更新人')),
                ('pinstance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekworkplan', to='lbworkflow.ProcessInstance', verbose_name='Process instance')),
                ('place', models.ForeignKey(on_delete=models.SET('systemsettings.Company'), related_name='周期检测计划公司名称', to='systemsettings.Company', verbose_name='公司名称')),
                ('planner', models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='检测计划策划人', to='systemsettings.MyUser', verbose_name='策划人')),
            ],
            options={
                'verbose_name': '周期检测计划',
            },
        ),
    ]
