# Generated by Django 2.0.5 on 2019-02-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekworkplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekworkplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='主键'),
        ),
    ]
