# Generated by Django 2.0.5 on 2019-02-26 11:00

from django.db import migrations, models
import systemsettings.models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0004_supervisiontype_form_use'),
        ('weekworkplan', '0002_auto_20190214_1558'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='weekworkplan',
    #         name='supervision_major',
    #         field=models.ForeignKey(default=1, null=True, on_delete=models.SET(systemsettings.models.SupervisionType), to='systemsettings.SupervisionType', verbose_name='监督专业'),
    #     ),
    # ]
