# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='联系方式')),
                ('net_name', models.SmallIntegerField(verbose_name='监督网络岗位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('is_activate', models.SmallIntegerField(default=1, null=True, verbose_name='是否激活')),
                ('work_type', models.CharField(default='网络人员信息', max_length=10, verbose_name='工单类型')),
            ],
            options={
                'verbose_name': '网络人员维护',
            },
        ),
    ]
