# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models
import django.db.models.deletion
import netstructure.models
import systemsettings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemsettings', '0001_initial'),
        ('netstaff', '0001_initial'),
        ('netstructure', '0001_initial'),
        ('lbworkflow', '0002_auto_20171019_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='netstaff',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(systemsettings.models.MyUser), related_name='监督网络人员信息表创建人', to='systemsettings.MyUser', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='netstaff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.Department), to='systemsettings.Department', verbose_name='所在部门'),
        ),
        migrations.AddField(
            model_name='netstaff',
            name='last_updated_by',
            field=models.ForeignKey(on_delete=models.SET(systemsettings.models.MyUser), related_name='监督网络人员信息表最后更新人', to='systemsettings.MyUser', verbose_name='最后更新人'),
        ),
        migrations.AddField(
            model_name='netstaff',
            name='netstructure',
            field=models.ForeignKey(on_delete=models.SET(netstructure.models.NetStructure), to='netstructure.NetStructure', verbose_name='所属监督网络'),
        ),
        migrations.AddField(
            model_name='netstaff',
            name='pinstance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='netstaff', to='lbworkflow.ProcessInstance', verbose_name='Process instance'),
        ),
        migrations.AddField(
            model_name='netstaff',
            name='place',
            field=models.ForeignKey(on_delete=models.SET(systemsettings.models.Company), related_name='网络人员公司名称', to='systemsettings.Company', verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='netstaff',
            name='user',
            field=models.ManyToManyField(to='systemsettings.MyUser', verbose_name='对应人员'),
        ),
    ]
