# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonWorkExe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('number', models.CharField(max_length=30, verbose_name='月度工作执行编码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('plan_content', models.CharField(max_length=200, verbose_name='计划工作内容')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='计划完成时间')),
                ('execute_desc', models.CharField(max_length=200, null=True, verbose_name='执行情况')),
                ('problem_desc', models.CharField(max_length=200, null=True, verbose_name='存在问题')),
                ('remarks', models.CharField(max_length=200, null=True, verbose_name='备注')),
                ('is_activate', models.SmallIntegerField(default=1, null=True, verbose_name='是否激活')),
                ('state', models.CharField(default='新建', max_length=10, verbose_name='状态')),
                ('work_type', models.CharField(default='月度工作执行', max_length=10, verbose_name='工单类型')),
            ],
            options={
                'verbose_name': '月度工作执行',
            },
        ),
    ]
