# Generated by Django 2.0.5 on 2018-08-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monworkexe', '0003_auto_20180820_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monworkexe',
            name='last_updated_by',
        ),
    ]
