# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='网络结构编号')),
                ('desc', models.CharField(max_length=50, null=True, verbose_name='描述')),
                ('classify', models.CharField(max_length=10, verbose_name='类别')),
                ('state', models.CharField(default='新建', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_activate', models.SmallIntegerField(default=1, null=True, verbose_name='是否激活')),
                ('last_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('work_type', models.CharField(default='网络结构信息', max_length=10, verbose_name='工单类型')),
                ('level', models.SmallIntegerField(null=True, verbose_name='监督网络级别')),
            ],
            options={
                'verbose_name': '网络结构信息',
            },
        ),
    ]
