# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemsettings', '0001_initial'),
        ('netstructure', '0001_initial'),
        ('lbworkflow', '0002_auto_20171019_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='netstructure',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='网络结构创建人', to='systemsettings.MyUser', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='netstructure',
            name='last_updated_by',
            field=models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='网络结构最后更新人', to='systemsettings.MyUser', verbose_name='最后更新人'),
        ),
        migrations.AddField(
            model_name='netstructure',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=models.SET('self'), to='netstructure.NetStructure', verbose_name='上级监督网络'),
        ),
        migrations.AddField(
            model_name='netstructure',
            name='pinstance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='netstructure', to='lbworkflow.ProcessInstance', verbose_name='Process instance'),
        ),
        migrations.AddField(
            model_name='netstructure',
            name='place',
            field=models.ForeignKey(on_delete=models.SET('systemsettings.Company'), related_name='监督网络公司名称', to='systemsettings.Company', verbose_name='公司名称'),
        ),
    ]
