# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models
import django.db.models.deletion
import problemlog.models
import systemsettings.models
import warning.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemsettings', '0001_initial'),
        ('problemlog', '0002_auto_20180806_1423'),
        ('lbworkflow', '0002_auto_20171019_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('state', models.CharField(default='新建', max_length=10, verbose_name='状态')),
                ('number', models.CharField(max_length=30, verbose_name='告警通知单编码')),
                ('enclosure', models.FileField(null=True, upload_to='Warning/', verbose_name='附件')),
                ('title', models.CharField(max_length=20, verbose_name='告警通知单名称')),
                ('abnormal', models.CharField(max_length=200, verbose_name='异常情况')),
                ('result', models.CharField(max_length=200, verbose_name='可能或已经造成的后果')),
                ('suggest', models.CharField(max_length=200, verbose_name='整改建议')),
                ('time_require', models.CharField(max_length=200, verbose_name='整改时间要求')),
                ('is_activate', models.SmallIntegerField(default=1, null=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('work_type', models.CharField(default='告警通知单', max_length=10, verbose_name='工单类型')),
                ('created_by', models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='告警通知单创建人', to='systemsettings.MyUser', verbose_name='创建人')),
                ('equipment', models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.KKS), to='systemsettings.KKS', verbose_name='关联设备')),
                ('exetuct_user', models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='告警责任人', to='systemsettings.MyUser', verbose_name='责任人')),
                ('last_updated_by', models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), to='systemsettings.MyUser', verbose_name='告警通知单最后更新人')),
                ('pinstance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warningnotice', to='lbworkflow.ProcessInstance', verbose_name='Process instance')),
                ('place', models.ForeignKey(on_delete=models.SET('systemsettings.Company'), to='systemsettings.Company', verbose_name='公司名称')),
                ('problem', models.ForeignKey(null=True, on_delete=models.SET(problemlog.models.Problemlog), to='problemlog.Problemlog', verbose_name='关联问题')),
            ],
            options={
                'verbose_name': '告警通知单',
            },
        ),
        migrations.CreateModel(
            name='WarningResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15, verbose_name='告警来源类')),
            ],
        ),
        migrations.AddField(
            model_name='warningnotice',
            name='resource',
            field=models.ForeignKey(default='', on_delete=models.SET(warning.models.WarningResource), to='warning.WarningResource', verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='warningnotice',
            name='supervise_major',
            field=models.ForeignKey(on_delete=models.SET(systemsettings.models.SupervisionType), to='systemsettings.SupervisionType', verbose_name='监督类型'),
        ),
    ]
