# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='资质编码')),
                ('name', models.CharField(max_length=30, verbose_name='资质名称')),
                ('warining_time', models.IntegerField(default=0, null=True, verbose_name='提前提醒天数')),
                ('is_activate', models.SmallIntegerField(default=1, null=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '资质编码表',
            },
        ),
    ]
