# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemsettings', '0001_initial'),
        ('qua25', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qua',
            name='place',
            field=models.ForeignKey(on_delete=models.SET('systemsettings.Company'), related_name='技术监督资质公司名称', to='systemsettings.Company', verbose_name='公司名称'),
        ),
    ]
