# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models
import quatype.models


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('qua25', '0002_qua_place'),
    #     ('quatype', '0001_initial'),
    # ]
    #
    # operations = [
    #     migrations.AddField(
    #         model_name='qua',
    #         name='qua_type',
    #         field=models.ForeignKey(on_delete=models.SET(quatype.models.QuaType), related_name='技术监督资质资质类型', to='quatype.QuaType', verbose_name='资质类型'),
    #     ),
    # ]
