# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models
import regularworkplan.models
import systemsettings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemsettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='工作准备序号')),
                ('content', models.TextField(verbose_name='工作准备内容')),
                ('KKS', models.ForeignKey(on_delete=models.SET(systemsettings.models.KKS), to='systemsettings.KKS', verbose_name='KKS编码')),
            ],
        ),
        migrations.CreateModel(
            name='RegularWorkPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='定期工作编码')),
                ('KKS_codename', models.CharField(max_length=30, null=True, verbose_name='KKS编码名称')),
                ('nature', models.CharField(max_length=10, null=True, verbose_name='性质')),
                ('type', models.CharField(max_length=10, verbose_name='定期工作类型')),
                ('score', models.IntegerField(default=0, null=True, verbose_name='标准分值')),
                ('work_content', models.TextField(max_length=200, verbose_name='工作项目')),
                ('weekend_desc', models.CharField(max_length=30, verbose_name='周期描述')),
                ('warinig_time', models.SmallIntegerField(verbose_name='提前提醒时间')),
                ('state', models.CharField(default='拟定', max_length=10, null=True, verbose_name='状态')),
                ('overdue_1', models.SmallIntegerField(null=True, verbose_name='超期一级预警')),
                ('overdue_2', models.SmallIntegerField(null=True, verbose_name='超期二级预警')),
                ('overdue_3', models.SmallIntegerField(null=True, verbose_name='超期三级预警')),
                ('resource', models.CharField(max_length=10, null=True, verbose_name='业务来源')),
                ('start_time', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('is_activate', models.SmallIntegerField(default=1, verbose_name='是否激活')),
                ('stard_smallnumber', models.CharField(max_length=30, null=True, verbose_name='标准号')),
                ('KKS_code', models.ForeignKey(on_delete=models.SET(systemsettings.models.KKS), to='systemsettings.KKS', verbose_name='KKS编码')),
                ('equipment_major', models.ForeignKey(on_delete=models.SET(systemsettings.models.EquipmentMajor), to='systemsettings.EquipmentMajor', verbose_name='设备专业')),
                ('exe_group', models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.MyGroup), to='systemsettings.MyGroup', verbose_name='责任组')),
                ('exe_user', models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.MyUser), to='systemsettings.MyUser', verbose_name='责任人')),
                ('place', models.ForeignKey(on_delete=models.SET(systemsettings.models.Company), to='systemsettings.Company', verbose_name='公司名称')),
                ('stard', models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.Stard), to='systemsettings.Stard', verbose_name='标准编码')),
                ('supervision_major', models.ForeignKey(null=True, on_delete=models.SET(systemsettings.models.SupervisionType), to='systemsettings.SupervisionType', verbose_name='监督专业')),
            ],
            options={
                'verbose_name': '定期工作策划主信息表',
            },
        ),
        migrations.CreateModel(
            name='WorkCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='注意事项序号')),
                ('content', models.TextField(verbose_name='注意事项内容')),
                ('KKS', models.ForeignKey(on_delete=models.SET(systemsettings.models.KKS), to='systemsettings.KKS', verbose_name='KKS编码')),
                ('regular_work', models.ForeignKey(on_delete=models.SET(regularworkplan.models.RegularWorkPlan), to='regularworkplan.RegularWorkPlan', verbose_name='定期工作策划')),
            ],
        ),
        migrations.CreateModel(
            name='WorkContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='工作内容序号')),
                ('content', models.TextField(verbose_name='工作内容')),
                ('KKS', models.ForeignKey(on_delete=models.SET(systemsettings.models.KKS), to='systemsettings.KKS', verbose_name='KKS编码')),
                ('regular_work', models.ForeignKey(on_delete=models.SET(regularworkplan.models.RegularWorkPlan), to='regularworkplan.RegularWorkPlan', verbose_name='定期工作策划')),
            ],
        ),
        migrations.AddField(
            model_name='prework',
            name='regular_work',
            field=models.ForeignKey(on_delete=models.SET(regularworkplan.models.RegularWorkPlan), to='regularworkplan.RegularWorkPlan', verbose_name='定期工作策划'),
        ),
    ]
