# Generated by Django 2.0.5 on 2018-08-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworkplan', '0002_auto_20180806_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularworkplan',
            name='num1',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='周期描述1'),
        ),
        migrations.AddField(
            model_name='regularworkplan',
            name='num2',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='周期描述2'),
        ),
    ]
