# Generated by Django 2.0.5 on 2018-08-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworkplan', '0003_auto_20180811_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularworkplan',
            name='num1',
            field=models.CharField(default='0', max_length=50, null=True, verbose_name='周期描述1'),
        ),
        migrations.AlterField(
            model_name='regularworkplan',
            name='num2',
            field=models.CharField(default='0', max_length=50, null=True, verbose_name='周期描述2'),
        ),
    ]
