# Generated by Django 2.0.5 on 2019-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworkplan', '0007_auto_20181006_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularworkplan',
            name='resource',
            field=models.CharField(max_length=50, null=True, verbose_name='业务来源'),
        ),
    ]
