# Generated by Django 2.0.5 on 2019-02-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworkplan', '0008_auto_20190118_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularworkplan',
            name='KKS_codename',
            field=models.CharField(max_length=1000, null=True, verbose_name='KKS编码名称'),
        ),
    ]
