# Generated by Django 2.0.5 on 2019-03-27 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regularworkplan', '0009_auto_20190227_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularworkplan',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularworkplan',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
    ]
