# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonPlanSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('desc', models.CharField(max_length=50, null=True, verbose_name='计划描述')),
                ('number', models.CharField(max_length=30, verbose_name='计划编码')),
                ('year', models.CharField(max_length=5, verbose_name='年份')),
                ('month', models.CharField(max_length=5, verbose_name='月份')),
                ('state', models.CharField(default='拟定', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('enclosure', models.FileField(null=True, upload_to='Plan/', verbose_name='附件')),
                ('is_activate', models.SmallIntegerField(default=1, null=True, verbose_name='是否激活')),
                ('work_type', models.CharField(default='月度计划与总结', max_length=10, verbose_name='工单类型')),
            ],
            options={
                'verbose_name': '月度计划与总结',
            },
        ),
        migrations.CreateModel(
            name='SmallDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallnumber', models.CharField(max_length=30, verbose_name='月度计划记录号')),
                ('content', models.CharField(max_length=200, verbose_name='月度计划内容')),
                ('finish_time', models.DateTimeField(verbose_name='完成时间')),
                ('is_activate', models.SmallIntegerField(default=1, verbose_name='是否活动')),
            ],
        ),
    ]
