# Generated by Django 2.0.5 on 2018-08-06 14:23

from django.db import migrations, models
import django.db.models.deletion
import mon_plan_sum.models
import systemsettings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemsettings', '0001_initial'),
        ('mon_plan_sum', '0001_initial'),
        ('lbworkflow', '0002_auto_20171019_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='smalldatas',
            name='exe_user',
            field=models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='责任人', to='systemsettings.MyUser', verbose_name='责任人'),
        ),
        migrations.AddField(
            model_name='smalldatas',
            name='monplansum',
            field=models.ForeignKey(on_delete=models.SET(mon_plan_sum.models.MonPlanSum), to='mon_plan_sum.MonPlanSum', verbose_name='月度计划编码'),
        ),
        migrations.AddField(
            model_name='monplansum',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='月度计划与总结创建人', to='systemsettings.MyUser', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='monplansum',
            name='last_updated_by',
            field=models.ForeignKey(on_delete=models.SET('systemsettings.MyUser'), related_name='月度计划与总结最后更新人', to='systemsettings.MyUser', verbose_name='最后更新人'),
        ),
        migrations.AddField(
            model_name='monplansum',
            name='pinstance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monplansum', to='lbworkflow.ProcessInstance', verbose_name='Process instance'),
        ),
        migrations.AddField(
            model_name='monplansum',
            name='place',
            field=models.ForeignKey(on_delete=models.SET('systemsettings.Company'), related_name='月度工作计划公司名称', to='systemsettings.Company', verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='monplansum',
            name='supervision_major',
            field=models.ForeignKey(on_delete=models.SET(systemsettings.models.SupervisionType), to='systemsettings.SupervisionType', verbose_name='监督类型'),
        ),
    ]
