# Generated by Django 2.0.5 on 2018-08-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworktask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularworktask',
            name='is_activate',
            field=models.SmallIntegerField(default=1, null=True, verbose_name='是否激活'),
        ),
    ]
