# Generated by Django 2.0.5 on 2018-08-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0001_initial'),
        ('regularworktask', '0002_regularworktask_is_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularworktask',
            name='place',
            field=models.ForeignKey(default='', on_delete=models.SET('systemsettings.Company'), to='systemsettings.Company', verbose_name='公司名称'),
        ),
    ]
