# Generated by Django 2.0.5 on 2018-08-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regularworktask', '0003_regularworktask_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularworktask',
            options={'verbose_name': '定期工作任务'},
        ),
    ]
