# Generated by Django 2.0.5 on 2018-08-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworktask', '0004_auto_20180808_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularworktask',
            name='regularwork',
            field=models.ForeignKey(on_delete=models.SET('regularworkplan.RegularWorkPlan'), to='regularworkplan.RegularWorkPlan', verbose_name='定期工作任务'),
        ),
    ]
