# Generated by Django 2.0.5 on 2018-08-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworktask', '0005_auto_20180816_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularworktask',
            name='tanchuang',
            field=models.SmallIntegerField(default='0', verbose_name='是否已弹窗'),
        ),
    ]
