# Generated by Django 2.0.5 on 2018-08-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworktask', '0007_regularworktask_has_readed'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='regularworktask',
    #         name='has_readed',
    #         field=models.SmallIntegerField(default='0', null=True, verbose_name='是否已读'),
    #     ),
    # ]
