# Generated by Django 2.0.5 on 2018-09-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworktask', '0008_auto_20180827_1616'),
    ]

    operations = [

        migrations.AlterField(
            model_name='regularworktask',
            name='tanchuang',
            field=models.SmallIntegerField(default='0', null=True, verbose_name='是否已弹窗'),
        ),
    ]
