# Generated by Django 2.0.5 on 2018-10-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworktask', '0009_auto_20180901_1548'),
    ]

#     operations = [
#         migrations.AddField(
#             model_name='regularworktask',
#             name='has_readed',
#             field=models.SmallIntegerField(default='0', null=True, verbose_name='是否已读'),
#         ),
#     ]
