# Generated by Django 2.0.5 on 2019-02-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworktask', '0010_regularworktask_has_readed'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularworktask',
            name='enclosure_file',
            field=models.FileField(null=True, upload_to='./media/task_enclosure_files', verbose_name='附件'),
        ),
    ]
