# Generated by Django 2.0.5 on 2019-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworktask', '0011_regularworktask_enclosure_file'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='regularworktask',
        #     name='has_readed',
        #     field=models.SmallIntegerField(default='0', null=True, verbose_name='是否已读'),
        # ),
        migrations.AlterField(
            model_name='regularworktask',
            name='enclosure_file',
            field=models.FileField(null=True, upload_to='./task_enclosure_files', verbose_name='附件'),
        ),
    ]
