# Generated by Django 2.0.5 on 2019-03-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularworktask', '0012_auto_20190227_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularworktask',
            name='has_readed',
            field=models.SmallIntegerField(default='0', null=True, verbose_name='是否已读'),
        ),
    ]
